version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - "${DOCKER_APP_PORT}"
    volumes:
      - .:/data

  redis:
    image: redis
    restart: always
    ports:
      - '${DOCKER_REDIS_PORT}'
    volumes:
      - .:/data

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '${DOCKER_POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - .:/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORTS}
    depends_on:
      - postgres

volumes:
  cache:
    driver: local