version: '3'

services:
  app:
    build: .
    ports:
      - "${DOCKER_APP_PORT}:${DOCKER_APP_PORT}"
    volumes:
      - .:/data

  redis:
    image: redis
    restart: always
    ports:
      - '${DOCKER_REDIS_PORT}:${DOCKER_REDIS_PORT}'
    volumes:
      - .:/data

  postgres:
    image: postgres
    restart: always
    ports:
      - '${DOCKER_POSTGRES_PORT}:${DOCKER_POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - .:/data

volumes:
  cache:
    driver: local