version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/data

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - .:/data

  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    volumes:
      - .:/data

volumes:
  cache:
    driver: local