"""Fix relationship

Revision ID: 0303d104bb73
Revises: 1b59cdfce2ed
Create Date: 2022-11-08 13:14:36.950359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0303d104bb73'
down_revision = '1b59cdfce2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question')
    # ### end Alembic commands ###
