"""Try another way

Revision ID: 045b06efae82
Revises: 25bf1e06fce7
Create Date: 2022-11-02 14:57:25.244457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045b06efae82'
down_revision = '25bf1e06fce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
