"""Try another way

Revision ID: 14cb893b1e91
Revises: bc685db445f7
Create Date: 2022-11-02 17:09:01.417749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14cb893b1e91'
down_revision = 'bc685db445f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
