"""Try another way

Revision ID: 184f86601c2e
Revises: ef37b50c14bd
Create Date: 2022-11-02 15:05:28.900209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184f86601c2e'
down_revision = 'ef37b50c14bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
