"""Try another way

Revision ID: 240a27a2686f
Revises: 14cb893b1e91
Create Date: 2022-11-02 17:10:49.279596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240a27a2686f'
down_revision = '14cb893b1e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
