"""Try another way

Revision ID: 25bf1e06fce7
Revises: dd41a8fda242
Create Date: 2022-11-02 14:25:30.828544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bf1e06fce7'
down_revision = 'dd41a8fda242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies_users', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies_users', 'id')
    # ### end Alembic commands ###
