"""Edit DbResult

Revision ID: 27d8af56bf86
Revises: b256ee87e201
Create Date: 2022-11-08 19:17:14.297064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27d8af56bf86'
down_revision = 'b256ee87e201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('questions', sa.Integer(), nullable=False))
    op.add_column('results', sa.Column('right_answers', sa.Integer(), nullable=False))
    op.drop_column('results', 'result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('result', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.drop_column('results', 'right_answers')
    op.drop_column('results', 'questions')
    # ### end Alembic commands ###
