"""Removed unnecessary

Revision ID: 2f8e39eb08ce
Revises: db2908f62bab
Create Date: 2022-11-04 10:47:11.659300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8e39eb08ce'
down_revision = 'db2908f62bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
