"""Fix relationships

Revision ID: 4eb0aec5f4d4
Revises: b4378f9d742b
Create Date: 2022-11-02 10:08:14.149920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb0aec5f4d4'
down_revision = 'b4378f9d742b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
