"""Try another way

Revision ID: 92917e4c870c
Revises: 184f86601c2e
Create Date: 2022-11-02 15:07:39.855254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92917e4c870c'
down_revision = '184f86601c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
