"""Fix relationships

Revision ID: 93dec6d9837d
Revises: 4eb0aec5f4d4
Create Date: 2022-11-02 11:22:48.693790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93dec6d9837d'
down_revision = '4eb0aec5f4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('companies_users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies_users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('companies_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
