"""New Migration

Revision ID: a5f5b045a90c
Revises: 743a8d528d78
Create Date: 2022-10-17 11:24:57.758201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f5b045a90c'
down_revision = '743a8d528d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
