"""Try another way

Revision ID: ae78e9e30b10
Revises: 240a27a2686f
Create Date: 2022-11-03 07:39:52.644236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae78e9e30b10'
down_revision = '240a27a2686f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies_administrators', 'id')
    op.drop_column('companies_users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies_users', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('companies_administrators', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
