"""Delete association question-quiz

Revision ID: b256ee87e201
Revises: 03986d489489
Create Date: 2022-11-08 17:18:09.097602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b256ee87e201'
down_revision = '03986d489489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_quiz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_quiz',
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='question_quiz_question_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='question_quiz_quiz_id_fkey')
    )
    # ### end Alembic commands ###
