"""Fix relationships

Revision ID: b4378f9d742b
Revises: e0671cf2d54a
Create Date: 2022-11-02 10:03:00.208341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4378f9d742b'
down_revision = 'e0671cf2d54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
