"""Try another way

Revision ID: bc685db445f7
Revises: 92917e4c870c
Create Date: 2022-11-02 17:01:43.798821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc685db445f7'
down_revision = '92917e4c870c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
