"""Try another way

Revision ID: dd41a8fda242
Revises: 93dec6d9837d
Create Date: 2022-11-02 14:24:19.940732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd41a8fda242'
down_revision = '93dec6d9837d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies_administrators', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('companies_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('companies_users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies_users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('companies_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('companies_administrators', 'id')
    # ### end Alembic commands ###
