"""Try another way

Revision ID: ef37b50c14bd
Revises: 045b06efae82
Create Date: 2022-11-02 15:04:52.211859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef37b50c14bd'
down_revision = '045b06efae82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
